-- Uploading the data to sql

create table 
	dim_room(
	room_id	varchar(10)  ,
	room_class varchar(20),	
primary key(room_id),
FOREIGN KEY (room_class) REFERENCES fact_booking (booking_id) 
);

create table 
	fact_booking(
	booking_id	varchar(30), 
	property_id	int,
	booking_date date,
	check_in_date date,
	checkout_date date,
	no_guests int,
	room_category varchar(5),
	booking_platform varchar(20),
	ratings_given int,
	booking_status	varchar(30),
	revenue_generated	int,
	revenue_realized int,
primary key(booking_id),
foreign key (property_id) references dim_hotels (property_id)
);

create table 
	fact_aggregate_booking(
	property_id int,
	check_in_date date,
	room_category varchar(10),
	successful_bookings int,
	capacity int,
foreign key(property_id) references dim_hotels(property_id)
);

create table 
	dim_date (
	id  serial primary key,
	date date,
	week_no varchar(20),
	day_type varchar(20)
);



create table 
	dim_hotels (property_id int,
	property_name varchar (20),
	category varchar (20),
	city varchar(20),
primary key (property_id)
);

  -- data cleaning

UPDATE fact_booking 
SET room_category ='Stnrd'
WHERE room_category ='RT1'

UPDATE fact_booking
set room_category ='Elite'
where room_category ='RT2'

UPDATE fact_booking
set room_category ='Premi'
where room_category ='RT3'

UPDATE fact_booking
set room_category ='Presi'
where room_category ='RT4'


UPDATE fact_booking
SET ratings_given =0
WHERE ratings_given IS NULL;

--number of successful booking days

select 
	count(successful_bookings)
from fact_aggregate_booking fab 

--maximun successful_booking checked_in_date

select 
	max(successful_bookings), check_in_date 
from fact_aggregate_booking fab
group by check_in_date 
order by 2
limit 1

-- Total successful booking
select 
	sum(successful_bookings)
from fact_aggregate_booking fab 

--maximum/min/total/avg revenue realised

select 
	max(revenue_realized) max_revenue,
	min(revenue_realized) min_revenue,
	sum(revenue_realized) total_revenue,
	avg(revenue_realized) average_revenue
from fact_booking

--maximum/min/total/avg revenue generated

select
	max(revenue_generated) max_generated,
	min(revenue_generated) min_generated,
	sum(revenue_generated) total_generated,
	avg(revenue_generated) average_generated
from fact_booking

--maximum/min/total/avg revenue generated by each state

select 
	max(revenue_generated) max_generated,
	min(revenue_generated) min_generated,
	sum(revenue_generated) total_generated,
	avg(revenue_generated) average_generated,
	city
from fact_booking fb
join dim_hotels dh 
on dh.property_id = fb.property_id 
group by city order by total_generated desc

--The maximum / total amount generated

select
	max(total_generated) as max_total_amt_genereated
from(
	select
		sum(revenue_generated) total_generated
	from fact_booking fb
	join dim_hotels dh 
	on dh.property_id = fb.property_id 
	group by city) ctl;

--maximum successful booking and total revenue realized

select 
	max(successful_bookings) max_Sbooking, 
	min(successful_bookings)min_Sbooking ,
	revenue_realized, checkout_date 
from fact_booking fab 
join fact_aggregate_booking  dh 
on fab.property_id = dh.property_id 
group by 3, 4
order by 1 desc 
limit 1

--earliest booking

select 
	min(check_in_date)
from fact_aggregate_booking fab 

--maximum/min/total/avg revenue generated by each property_name

select 
	max(revenue_generated) max_generated,
	min(revenue_generated) min_generated,
	sum(revenue_generated) total_generated,
	avg(revenue_generated) average_generated,
	property_name
from fact_booking fb
join dim_hotels dh 
on dh.property_id = fb.property_id 
group by property_name order by total_generated desc

--maximum/min/total/avg revenue generated by each category

select
	max(revenue_generated) max_generated,
	min(revenue_generated) min_generated,
	sum(revenue_generated) total_generated,
	avg(revenue_generated) average_generated,
	category
from fact_booking fb
join dim_hotels dh 
on dh.property_id = fb.property_id 
group by category order by total_generated desc

--maximum/ min/ avg/ totol amount realized from  all city, 

select Lagos.city,
	max(Lagos.total_realised)as max_city_TR,
	min(Lagos.total_realised)as man_city_TR,
	avg(Lagos.total_realised)as avg_city_TR,
	sum(lagos.total_realised) as sum_city_TR
from
    (
	select
		sum(revenue_realized) total_realised,
		city,
		category,
		property_name
	from fact_booking fb
	join dim_hotels dh 
	on dh.property_id = fb.property_id 
	group by city, category,property_name
	)as Lagos
group by 1

--property_id with the highest booking

select 
	property_name, 
	sum(no_guests) total_num_no_guest
from fact_booking fb 
join dim_hotels dh 
on dh.property_id = fb.property_id 
group by 1
order by 2 desc



select 
	property_name, 
	sum(s) total_num_no_guest
from  
join dim_hotels dh 
on dh.property_id = fb.property_id 
group by 1
order by 2 desc

--total amount realised by each day of the wohole month

SELECT 
	DATE_PART('day', booking_date) booking_year,
	SUM(revenue_realized) total_day_realized
 FROM fact_booking fb 
 GROUP BY 1
 ORDER by 1


--total amount realizes by booking platform
 
 select
 	booking_platform,
 	sum(revenue_realized) total_revenue_realized
 from fact_booking fb 
 group by booking_platform
 order by total_revenue_realized desc
 
 
--total amount realizes by booking platform / city

 select
 	booking_platform,
 	city,
 	sum(revenue_realized) total_revenue_realized
 from fact_booking fb
 join dim_hotels dh 
 on dh.property_id = fb.property_id 
 group by booking_platform, city
 order by city, total_revenue_realized desc

 --max,min,avg amount realizes by booking platform / city
 
 select
 	city,
 	max(total_revenue_realized)max_amt_realized,
 	avg(total_revenue_realized) min_amt_realized,
 	min(total_revenue_realized) avg_amt_realized
 from(
 	select
 	booking_platform,
 	city,
 	sum(revenue_realized) total_revenue_realized
 	from fact_booking fb
 	join dim_hotels dh 
 	on dh.property_id = fb.property_id 
 	group by booking_platform, city
 	order by city, total_revenue_realized desc
 	)RL
 group by city
 
 
 --count of booking staus
  
 select
 	booking_status ,
 	count(booking_status)
 from fact_booking fb 
 group by booking_status 
 order by 2 desc
 	
 
 
--- room category count

select 
	room_category,
	count(room_category),
	sum(revenue_realized) Total_revenue_realized
from fact_booking fb 
group by room_category 
order by Total_revenue_realized

-- revenue_realized daily running total
 SELECT revenue_realized,
	DATE_TRUNC('day', booking_date) as day,
 	SUM(revenue_realized) OVER (PARTITION BY DATE_TRUNC('day', booking_date) 
 ORDER BY booking_date) AS running_total
 FROM fact_booking  

-- revenue_generated daily running data
  SELECT revenue_generated ,
	DATE_TRUNC('day', booking_date) as day,
 	SUM(revenue_generated) OVER (PARTITION BY DATE_TRUNC('day', booking_date) 
 ORDER BY booking_date) AS running_total
 FROM fact_booking  

----running total revenue realised, running booking count/ average revenue count
 
 SELECT property_id,
 		booking_date,
       revenue_realized,
       revenue_generated,
       SUM(revenue_realized) OVER
           (PARTITION BY date_trunc('month', booking_date) 
           ORDER BY booking_date) AS running_monthly_revenue_R,
       COUNT(property_id) OVER
           (PARTITION BY date_trunc('month',booking_date) 
           ORDER BY booking_date) AS running_monthly_booking,
       AVG(revenue_generated) OVER
           (PARTITION BY date_trunc('month',booking_date)
           ORDER BY booking_date) AS average_monthly_revenue_generated
FROM  fact_booking fb 

--HOTEL WITH  RATING count

select
	city,
	property_name,
	ratings_given,
	count(ratings_given) rating_count
from dim_hotels dh 
join fact_booking fb 
on dh.property_id = fb.property_id 
group by property_name,city ,ratings_given
--having ratings_given = 0
order by ratings_given desc, rating_count desc



-- people that checked in each day  
select 
	successful_bookings, 
	property_id,
	check_in_date , 
count(check_in_date ) Num_of_people_that_checkin
from fact_aggregate_booking fab
group by property_id , check_in_date, successful_bookings  
order by 4 desc
